### ISSUE TITLE
大佬您好，如何使用drools-drt生成参数类型为decimal数据类型的规则？

### ISSUE THREAD

**Issue by DripRank** [247292980/spring-boot#1]
数据库中存储的规则中 有decimal规则 使用drools-drt改变数据库参数如
![图片](https://user-images.githubusercontent.com/49722000/56291664-425e3f80-6158-11e9-8df9-cfe3a221af25.png)
加载规则时报错

**Comment by 247292980** [comment]
你的报错是什么?
